runtime: custom
env: flex
entrypoint: gunicorn -b :$PORT main:app

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2

resources:
  cpu: 1
  memory_gb: 3.6
  disk_size_gb: 20

# entrypoint: gunicorn -b :$PORT main:app
#
# runtime_config:
#  python_version: 3.8